### ISSUE TITLE
modify ssm editable secrets to allow group of developers to edit variables under certain path

### ISSUE THREAD

**Issue by qbart** [Selleo/terraform-aws-ssm#2]
https://github.com/Selleo/terraform-aws-ssm/blob/main/modules/editable-parameters/main.tf

**Comment by Jlkan** [comment]
https://github.com/Selleo/terraform-aws-ecr/blob/v0.5.0/modules/repository/main.tf

**Comment by Jlkan** [comment]
add permission as iam.tf
